const OK_STATUS_CODE = 200;
const CREATED_STATUS_CODE = 201;
const BAD_REQUEST_ERROR_CODE = 400;
const AUTHORIZATION_ERROR_CODE = 401;
const ALIEN_ARTICLE_ERROR_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const EMAIL_EXISTS_ERROR_CODE = 409;
const DEFAULT_ERROR_CODE = 500;
const DUPLICATE_KEY_ERROR_CODE = 11000;

module.exports = {
  OK_STATUS_CODE,
  CREATED_STATUS_CODE,
  BAD_REQUEST_ERROR_CODE,
  AUTHORIZATION_ERROR_CODE,
  ALIEN_ARTICLE_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  EMAIL_EXISTS_ERROR_CODE,
  DUPLICATE_KEY_ERROR_CODE,
  DEFAULT_ERROR_CODE,
};
